#include "test.h"

/* テスト対象のモジュール */
#include "../mj_tile.h"
#include "../mj_utility.h"

#include <stddef.h>

void MJTileTest_Setup(void);

static int MJTileTest_Initialize(void *obj)
{
  TEST_UNUSED_PARAMETER(obj);
  return 0;
}

static int MJTileTest_Finalize(void *obj)
{
  TEST_UNUSED_PARAMETER(obj);
  return 0;
}

/* 字牌判定 */
MJUTILITY_STATIC_ASSERT(
       !MJTILE_IS_JIHAI(MJTILE_1MAN) && !MJTILE_IS_JIHAI(MJTILE_2MAN)
    && !MJTILE_IS_JIHAI(MJTILE_3MAN) && !MJTILE_IS_JIHAI(MJTILE_4MAN)
    && !MJTILE_IS_JIHAI(MJTILE_5MAN) && !MJTILE_IS_JIHAI(MJTILE_6MAN)
    && !MJTILE_IS_JIHAI(MJTILE_7MAN) && !MJTILE_IS_JIHAI(MJTILE_8MAN)
    && !MJTILE_IS_JIHAI(MJTILE_9MAN)
    && !MJTILE_IS_JIHAI(MJTILE_1PIN) && !MJTILE_IS_JIHAI(MJTILE_2PIN)
    && !MJTILE_IS_JIHAI(MJTILE_3PIN) && !MJTILE_IS_JIHAI(MJTILE_4PIN)
    && !MJTILE_IS_JIHAI(MJTILE_5PIN) && !MJTILE_IS_JIHAI(MJTILE_6PIN)
    && !MJTILE_IS_JIHAI(MJTILE_7PIN) && !MJTILE_IS_JIHAI(MJTILE_8PIN)
    && !MJTILE_IS_JIHAI(MJTILE_9PIN)
    && !MJTILE_IS_JIHAI(MJTILE_1SOU) && !MJTILE_IS_JIHAI(MJTILE_2SOU)
    && !MJTILE_IS_JIHAI(MJTILE_3SOU) && !MJTILE_IS_JIHAI(MJTILE_4SOU)
    && !MJTILE_IS_JIHAI(MJTILE_5SOU) && !MJTILE_IS_JIHAI(MJTILE_6SOU)
    && !MJTILE_IS_JIHAI(MJTILE_7SOU) && !MJTILE_IS_JIHAI(MJTILE_8SOU)
    && !MJTILE_IS_JIHAI(MJTILE_9SOU)
    &&  MJTILE_IS_JIHAI(MJTILE_TON)  &&  MJTILE_IS_JIHAI(MJTILE_NAN)
    &&  MJTILE_IS_JIHAI(MJTILE_SHA)  &&  MJTILE_IS_JIHAI(MJTILE_PEE)
    &&  MJTILE_IS_JIHAI(MJTILE_HAKU) &&  MJTILE_IS_JIHAI(MJTILE_HATU)
    &&  MJTILE_IS_JIHAI(MJTILE_CHUN)
    );

/* 数牌判定 */
MJUTILITY_STATIC_ASSERT(
        MJTILE_IS_SUHAI(MJTILE_1MAN) &&  MJTILE_IS_SUHAI(MJTILE_2MAN)
    &&  MJTILE_IS_SUHAI(MJTILE_3MAN) &&  MJTILE_IS_SUHAI(MJTILE_4MAN)
    &&  MJTILE_IS_SUHAI(MJTILE_5MAN) &&  MJTILE_IS_SUHAI(MJTILE_6MAN)
    &&  MJTILE_IS_SUHAI(MJTILE_7MAN) &&  MJTILE_IS_SUHAI(MJTILE_8MAN)
    &&  MJTILE_IS_SUHAI(MJTILE_9MAN)
    &&  MJTILE_IS_SUHAI(MJTILE_1PIN) &&  MJTILE_IS_SUHAI(MJTILE_2PIN)
    &&  MJTILE_IS_SUHAI(MJTILE_3PIN) &&  MJTILE_IS_SUHAI(MJTILE_4PIN)
    &&  MJTILE_IS_SUHAI(MJTILE_5PIN) &&  MJTILE_IS_SUHAI(MJTILE_6PIN)
    &&  MJTILE_IS_SUHAI(MJTILE_7PIN) &&  MJTILE_IS_SUHAI(MJTILE_8PIN)
    &&  MJTILE_IS_SUHAI(MJTILE_9PIN)
    &&  MJTILE_IS_SUHAI(MJTILE_1SOU) &&  MJTILE_IS_SUHAI(MJTILE_2SOU)
    &&  MJTILE_IS_SUHAI(MJTILE_3SOU) &&  MJTILE_IS_SUHAI(MJTILE_4SOU)
    &&  MJTILE_IS_SUHAI(MJTILE_5SOU) &&  MJTILE_IS_SUHAI(MJTILE_6SOU)
    &&  MJTILE_IS_SUHAI(MJTILE_7SOU) &&  MJTILE_IS_SUHAI(MJTILE_8SOU)
    &&  MJTILE_IS_SUHAI(MJTILE_9SOU)
    && !MJTILE_IS_SUHAI(MJTILE_TON)  && !MJTILE_IS_SUHAI(MJTILE_NAN)
    && !MJTILE_IS_SUHAI(MJTILE_SHA)  && !MJTILE_IS_SUHAI(MJTILE_PEE)
    && !MJTILE_IS_SUHAI(MJTILE_HAKU) && !MJTILE_IS_SUHAI(MJTILE_HATU)
    && !MJTILE_IS_SUHAI(MJTILE_CHUN)
    );

/* 老頭牌判定 */
MJUTILITY_STATIC_ASSERT(
        MJTILE_IS_ROUTOU(MJTILE_1MAN) && !MJTILE_IS_ROUTOU(MJTILE_2MAN)
    && !MJTILE_IS_ROUTOU(MJTILE_3MAN) && !MJTILE_IS_ROUTOU(MJTILE_4MAN)
    && !MJTILE_IS_ROUTOU(MJTILE_5MAN) && !MJTILE_IS_ROUTOU(MJTILE_6MAN)
    && !MJTILE_IS_ROUTOU(MJTILE_7MAN) && !MJTILE_IS_ROUTOU(MJTILE_8MAN)
    &&  MJTILE_IS_ROUTOU(MJTILE_9MAN)
    &&  MJTILE_IS_ROUTOU(MJTILE_1PIN) && !MJTILE_IS_ROUTOU(MJTILE_2PIN)
    && !MJTILE_IS_ROUTOU(MJTILE_3PIN) && !MJTILE_IS_ROUTOU(MJTILE_4PIN)
    && !MJTILE_IS_ROUTOU(MJTILE_5PIN) && !MJTILE_IS_ROUTOU(MJTILE_6PIN)
    && !MJTILE_IS_ROUTOU(MJTILE_7PIN) && !MJTILE_IS_ROUTOU(MJTILE_8PIN)
    &&  MJTILE_IS_ROUTOU(MJTILE_9PIN)
    &&  MJTILE_IS_ROUTOU(MJTILE_1SOU) && !MJTILE_IS_ROUTOU(MJTILE_2SOU)
    && !MJTILE_IS_ROUTOU(MJTILE_3SOU) && !MJTILE_IS_ROUTOU(MJTILE_4SOU)
    && !MJTILE_IS_ROUTOU(MJTILE_5SOU) && !MJTILE_IS_ROUTOU(MJTILE_6SOU)
    && !MJTILE_IS_ROUTOU(MJTILE_7SOU) && !MJTILE_IS_ROUTOU(MJTILE_8SOU)
    &&  MJTILE_IS_ROUTOU(MJTILE_9SOU)
    && !MJTILE_IS_ROUTOU(MJTILE_TON)  && !MJTILE_IS_ROUTOU(MJTILE_NAN)
    && !MJTILE_IS_ROUTOU(MJTILE_SHA)  && !MJTILE_IS_ROUTOU(MJTILE_PEE)
    && !MJTILE_IS_ROUTOU(MJTILE_HAKU) && !MJTILE_IS_ROUTOU(MJTILE_HATU)
    && !MJTILE_IS_ROUTOU(MJTILE_CHUN)
    );

/* 中張牌判定 */
MJUTILITY_STATIC_ASSERT(
       !MJTILE_IS_CHUNCHAN(MJTILE_1MAN) &&  MJTILE_IS_CHUNCHAN(MJTILE_2MAN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_3MAN) &&  MJTILE_IS_CHUNCHAN(MJTILE_4MAN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_5MAN) &&  MJTILE_IS_CHUNCHAN(MJTILE_6MAN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_7MAN) &&  MJTILE_IS_CHUNCHAN(MJTILE_8MAN)
    && !MJTILE_IS_CHUNCHAN(MJTILE_9MAN)
    && !MJTILE_IS_CHUNCHAN(MJTILE_1PIN) &&  MJTILE_IS_CHUNCHAN(MJTILE_2PIN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_3PIN) &&  MJTILE_IS_CHUNCHAN(MJTILE_4PIN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_5PIN) &&  MJTILE_IS_CHUNCHAN(MJTILE_6PIN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_7PIN) &&  MJTILE_IS_CHUNCHAN(MJTILE_8PIN)
    && !MJTILE_IS_CHUNCHAN(MJTILE_9PIN)
    && !MJTILE_IS_CHUNCHAN(MJTILE_1SOU) &&  MJTILE_IS_CHUNCHAN(MJTILE_2SOU)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_3SOU) &&  MJTILE_IS_CHUNCHAN(MJTILE_4SOU)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_5SOU) &&  MJTILE_IS_CHUNCHAN(MJTILE_6SOU)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_7SOU) &&  MJTILE_IS_CHUNCHAN(MJTILE_8SOU)
    && !MJTILE_IS_CHUNCHAN(MJTILE_9SOU)
    && !MJTILE_IS_CHUNCHAN(MJTILE_TON)  && !MJTILE_IS_CHUNCHAN(MJTILE_NAN)
    && !MJTILE_IS_CHUNCHAN(MJTILE_SHA)  && !MJTILE_IS_CHUNCHAN(MJTILE_PEE)
    && !MJTILE_IS_CHUNCHAN(MJTILE_HAKU) && !MJTILE_IS_CHUNCHAN(MJTILE_HATU)
    && !MJTILE_IS_CHUNCHAN(MJTILE_CHUN)
    );

/* 么九牌判定 */
MJUTILITY_STATIC_ASSERT(
        MJTILE_IS_YAOCHU(MJTILE_1MAN) && !MJTILE_IS_YAOCHU(MJTILE_2MAN)
    && !MJTILE_IS_YAOCHU(MJTILE_3MAN) && !MJTILE_IS_YAOCHU(MJTILE_4MAN)
    && !MJTILE_IS_YAOCHU(MJTILE_5MAN) && !MJTILE_IS_YAOCHU(MJTILE_6MAN)
    && !MJTILE_IS_YAOCHU(MJTILE_7MAN) && !MJTILE_IS_YAOCHU(MJTILE_8MAN)
    &&  MJTILE_IS_YAOCHU(MJTILE_9MAN)
    &&  MJTILE_IS_YAOCHU(MJTILE_1PIN) && !MJTILE_IS_YAOCHU(MJTILE_2PIN)
    && !MJTILE_IS_YAOCHU(MJTILE_3PIN) && !MJTILE_IS_YAOCHU(MJTILE_4PIN)
    && !MJTILE_IS_YAOCHU(MJTILE_5PIN) && !MJTILE_IS_YAOCHU(MJTILE_6PIN)
    && !MJTILE_IS_YAOCHU(MJTILE_7PIN) && !MJTILE_IS_YAOCHU(MJTILE_8PIN)
    &&  MJTILE_IS_YAOCHU(MJTILE_9PIN)
    &&  MJTILE_IS_YAOCHU(MJTILE_1SOU) && !MJTILE_IS_YAOCHU(MJTILE_2SOU)
    && !MJTILE_IS_YAOCHU(MJTILE_3SOU) && !MJTILE_IS_YAOCHU(MJTILE_4SOU)
    && !MJTILE_IS_YAOCHU(MJTILE_5SOU) && !MJTILE_IS_YAOCHU(MJTILE_6SOU)
    && !MJTILE_IS_YAOCHU(MJTILE_7SOU) && !MJTILE_IS_YAOCHU(MJTILE_8SOU)
    &&  MJTILE_IS_YAOCHU(MJTILE_9SOU)
    &&  MJTILE_IS_YAOCHU(MJTILE_TON)  &&  MJTILE_IS_YAOCHU(MJTILE_NAN)
    &&  MJTILE_IS_YAOCHU(MJTILE_SHA)  &&  MJTILE_IS_YAOCHU(MJTILE_PEE)
    &&  MJTILE_IS_YAOCHU(MJTILE_HAKU) &&  MJTILE_IS_YAOCHU(MJTILE_HATU)
    &&  MJTILE_IS_YAOCHU(MJTILE_CHUN)
    );

/* 牌種の判定チェック */
static void MJTileTest_CheckTileTypeTest(void *obj)
{
  TEST_UNUSED_PARAMETER(obj);

  {
  }
}

void MJTileTest_Setup(void)
{
  struct TestSuite *suite
    = Test_AddTestSuite("MJ Tile Test Suite",
        NULL, MJTileTest_Initialize, MJTileTest_Finalize);

  Test_AddTest(suite, MJTileTest_CheckTileTypeTest);
}
