#include "test.h"

/* テスト対象のモジュール */
#include "../mj_tile.h"
#include "../mj_utility.h"

#include <stddef.h>

void MJTileTest_Setup(void);

static int MJTileTest_Initialize(void *obj)
{
  TEST_UNUSED_PARAMETER(obj);
  return 0;
}

static int MJTileTest_Finalize(void *obj)
{
  TEST_UNUSED_PARAMETER(obj);
  return 0;
}

/* 字牌判定 */
MJUTILITY_STATIC_ASSERT(
       !MJTILE_IS_JIHAI(MJTILE_1MAN) && !MJTILE_IS_JIHAI(MJTILE_2MAN)
    && !MJTILE_IS_JIHAI(MJTILE_3MAN) && !MJTILE_IS_JIHAI(MJTILE_4MAN)
    && !MJTILE_IS_JIHAI(MJTILE_5MAN) && !MJTILE_IS_JIHAI(MJTILE_6MAN)
    && !MJTILE_IS_JIHAI(MJTILE_7MAN) && !MJTILE_IS_JIHAI(MJTILE_8MAN)
    && !MJTILE_IS_JIHAI(MJTILE_9MAN)
    && !MJTILE_IS_JIHAI(MJTILE_1PIN) && !MJTILE_IS_JIHAI(MJTILE_2PIN)
    && !MJTILE_IS_JIHAI(MJTILE_3PIN) && !MJTILE_IS_JIHAI(MJTILE_4PIN)
    && !MJTILE_IS_JIHAI(MJTILE_5PIN) && !MJTILE_IS_JIHAI(MJTILE_6PIN)
    && !MJTILE_IS_JIHAI(MJTILE_7PIN) && !MJTILE_IS_JIHAI(MJTILE_8PIN)
    && !MJTILE_IS_JIHAI(MJTILE_9PIN)
    && !MJTILE_IS_JIHAI(MJTILE_1SOU) && !MJTILE_IS_JIHAI(MJTILE_2SOU)
    && !MJTILE_IS_JIHAI(MJTILE_3SOU) && !MJTILE_IS_JIHAI(MJTILE_4SOU)
    && !MJTILE_IS_JIHAI(MJTILE_5SOU) && !MJTILE_IS_JIHAI(MJTILE_6SOU)
    && !MJTILE_IS_JIHAI(MJTILE_7SOU) && !MJTILE_IS_JIHAI(MJTILE_8SOU)
    && !MJTILE_IS_JIHAI(MJTILE_9SOU)
    &&  MJTILE_IS_JIHAI(MJTILE_TON)  &&  MJTILE_IS_JIHAI(MJTILE_NAN)
    &&  MJTILE_IS_JIHAI(MJTILE_SHA)  &&  MJTILE_IS_JIHAI(MJTILE_PEE)
    &&  MJTILE_IS_JIHAI(MJTILE_HAKU) &&  MJTILE_IS_JIHAI(MJTILE_HATU)
    &&  MJTILE_IS_JIHAI(MJTILE_CHUN)
    );

/* 数牌判定 */
MJUTILITY_STATIC_ASSERT(
        MJTILE_IS_SUHAI(MJTILE_1MAN) &&  MJTILE_IS_SUHAI(MJTILE_2MAN)
    &&  MJTILE_IS_SUHAI(MJTILE_3MAN) &&  MJTILE_IS_SUHAI(MJTILE_4MAN)
    &&  MJTILE_IS_SUHAI(MJTILE_5MAN) &&  MJTILE_IS_SUHAI(MJTILE_6MAN)
    &&  MJTILE_IS_SUHAI(MJTILE_7MAN) &&  MJTILE_IS_SUHAI(MJTILE_8MAN)
    &&  MJTILE_IS_SUHAI(MJTILE_9MAN)
    &&  MJTILE_IS_SUHAI(MJTILE_1PIN) &&  MJTILE_IS_SUHAI(MJTILE_2PIN)
    &&  MJTILE_IS_SUHAI(MJTILE_3PIN) &&  MJTILE_IS_SUHAI(MJTILE_4PIN)
    &&  MJTILE_IS_SUHAI(MJTILE_5PIN) &&  MJTILE_IS_SUHAI(MJTILE_6PIN)
    &&  MJTILE_IS_SUHAI(MJTILE_7PIN) &&  MJTILE_IS_SUHAI(MJTILE_8PIN)
    &&  MJTILE_IS_SUHAI(MJTILE_9PIN)
    &&  MJTILE_IS_SUHAI(MJTILE_1SOU) &&  MJTILE_IS_SUHAI(MJTILE_2SOU)
    &&  MJTILE_IS_SUHAI(MJTILE_3SOU) &&  MJTILE_IS_SUHAI(MJTILE_4SOU)
    &&  MJTILE_IS_SUHAI(MJTILE_5SOU) &&  MJTILE_IS_SUHAI(MJTILE_6SOU)
    &&  MJTILE_IS_SUHAI(MJTILE_7SOU) &&  MJTILE_IS_SUHAI(MJTILE_8SOU)
    &&  MJTILE_IS_SUHAI(MJTILE_9SOU)
    && !MJTILE_IS_SUHAI(MJTILE_TON)  && !MJTILE_IS_SUHAI(MJTILE_NAN)
    && !MJTILE_IS_SUHAI(MJTILE_SHA)  && !MJTILE_IS_SUHAI(MJTILE_PEE)
    && !MJTILE_IS_SUHAI(MJTILE_HAKU) && !MJTILE_IS_SUHAI(MJTILE_HATU)
    && !MJTILE_IS_SUHAI(MJTILE_CHUN)
    );

/* 老頭牌判定 */
MJUTILITY_STATIC_ASSERT(
        MJTILE_IS_ROUTOU(MJTILE_1MAN) && !MJTILE_IS_ROUTOU(MJTILE_2MAN)
    && !MJTILE_IS_ROUTOU(MJTILE_3MAN) && !MJTILE_IS_ROUTOU(MJTILE_4MAN)
    && !MJTILE_IS_ROUTOU(MJTILE_5MAN) && !MJTILE_IS_ROUTOU(MJTILE_6MAN)
    && !MJTILE_IS_ROUTOU(MJTILE_7MAN) && !MJTILE_IS_ROUTOU(MJTILE_8MAN)
    &&  MJTILE_IS_ROUTOU(MJTILE_9MAN)
    &&  MJTILE_IS_ROUTOU(MJTILE_1PIN) && !MJTILE_IS_ROUTOU(MJTILE_2PIN)
    && !MJTILE_IS_ROUTOU(MJTILE_3PIN) && !MJTILE_IS_ROUTOU(MJTILE_4PIN)
    && !MJTILE_IS_ROUTOU(MJTILE_5PIN) && !MJTILE_IS_ROUTOU(MJTILE_6PIN)
    && !MJTILE_IS_ROUTOU(MJTILE_7PIN) && !MJTILE_IS_ROUTOU(MJTILE_8PIN)
    &&  MJTILE_IS_ROUTOU(MJTILE_9PIN)
    &&  MJTILE_IS_ROUTOU(MJTILE_1SOU) && !MJTILE_IS_ROUTOU(MJTILE_2SOU)
    && !MJTILE_IS_ROUTOU(MJTILE_3SOU) && !MJTILE_IS_ROUTOU(MJTILE_4SOU)
    && !MJTILE_IS_ROUTOU(MJTILE_5SOU) && !MJTILE_IS_ROUTOU(MJTILE_6SOU)
    && !MJTILE_IS_ROUTOU(MJTILE_7SOU) && !MJTILE_IS_ROUTOU(MJTILE_8SOU)
    &&  MJTILE_IS_ROUTOU(MJTILE_9SOU)
    && !MJTILE_IS_ROUTOU(MJTILE_TON)  && !MJTILE_IS_ROUTOU(MJTILE_NAN)
    && !MJTILE_IS_ROUTOU(MJTILE_SHA)  && !MJTILE_IS_ROUTOU(MJTILE_PEE)
    && !MJTILE_IS_ROUTOU(MJTILE_HAKU) && !MJTILE_IS_ROUTOU(MJTILE_HATU)
    && !MJTILE_IS_ROUTOU(MJTILE_CHUN)
    );

/* 中張牌判定 */
MJUTILITY_STATIC_ASSERT(
       !MJTILE_IS_CHUNCHAN(MJTILE_1MAN) &&  MJTILE_IS_CHUNCHAN(MJTILE_2MAN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_3MAN) &&  MJTILE_IS_CHUNCHAN(MJTILE_4MAN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_5MAN) &&  MJTILE_IS_CHUNCHAN(MJTILE_6MAN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_7MAN) &&  MJTILE_IS_CHUNCHAN(MJTILE_8MAN)
    && !MJTILE_IS_CHUNCHAN(MJTILE_9MAN)
    && !MJTILE_IS_CHUNCHAN(MJTILE_1PIN) &&  MJTILE_IS_CHUNCHAN(MJTILE_2PIN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_3PIN) &&  MJTILE_IS_CHUNCHAN(MJTILE_4PIN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_5PIN) &&  MJTILE_IS_CHUNCHAN(MJTILE_6PIN)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_7PIN) &&  MJTILE_IS_CHUNCHAN(MJTILE_8PIN)
    && !MJTILE_IS_CHUNCHAN(MJTILE_9PIN)
    && !MJTILE_IS_CHUNCHAN(MJTILE_1SOU) &&  MJTILE_IS_CHUNCHAN(MJTILE_2SOU)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_3SOU) &&  MJTILE_IS_CHUNCHAN(MJTILE_4SOU)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_5SOU) &&  MJTILE_IS_CHUNCHAN(MJTILE_6SOU)
    &&  MJTILE_IS_CHUNCHAN(MJTILE_7SOU) &&  MJTILE_IS_CHUNCHAN(MJTILE_8SOU)
    && !MJTILE_IS_CHUNCHAN(MJTILE_9SOU)
    && !MJTILE_IS_CHUNCHAN(MJTILE_TON)  && !MJTILE_IS_CHUNCHAN(MJTILE_NAN)
    && !MJTILE_IS_CHUNCHAN(MJTILE_SHA)  && !MJTILE_IS_CHUNCHAN(MJTILE_PEE)
    && !MJTILE_IS_CHUNCHAN(MJTILE_HAKU) && !MJTILE_IS_CHUNCHAN(MJTILE_HATU)
    && !MJTILE_IS_CHUNCHAN(MJTILE_CHUN)
    );

/* 么九牌判定 */
MJUTILITY_STATIC_ASSERT(
        MJTILE_IS_YAOCHU(MJTILE_1MAN) && !MJTILE_IS_YAOCHU(MJTILE_2MAN)
    && !MJTILE_IS_YAOCHU(MJTILE_3MAN) && !MJTILE_IS_YAOCHU(MJTILE_4MAN)
    && !MJTILE_IS_YAOCHU(MJTILE_5MAN) && !MJTILE_IS_YAOCHU(MJTILE_6MAN)
    && !MJTILE_IS_YAOCHU(MJTILE_7MAN) && !MJTILE_IS_YAOCHU(MJTILE_8MAN)
    &&  MJTILE_IS_YAOCHU(MJTILE_9MAN)
    &&  MJTILE_IS_YAOCHU(MJTILE_1PIN) && !MJTILE_IS_YAOCHU(MJTILE_2PIN)
    && !MJTILE_IS_YAOCHU(MJTILE_3PIN) && !MJTILE_IS_YAOCHU(MJTILE_4PIN)
    && !MJTILE_IS_YAOCHU(MJTILE_5PIN) && !MJTILE_IS_YAOCHU(MJTILE_6PIN)
    && !MJTILE_IS_YAOCHU(MJTILE_7PIN) && !MJTILE_IS_YAOCHU(MJTILE_8PIN)
    &&  MJTILE_IS_YAOCHU(MJTILE_9PIN)
    &&  MJTILE_IS_YAOCHU(MJTILE_1SOU) && !MJTILE_IS_YAOCHU(MJTILE_2SOU)
    && !MJTILE_IS_YAOCHU(MJTILE_3SOU) && !MJTILE_IS_YAOCHU(MJTILE_4SOU)
    && !MJTILE_IS_YAOCHU(MJTILE_5SOU) && !MJTILE_IS_YAOCHU(MJTILE_6SOU)
    && !MJTILE_IS_YAOCHU(MJTILE_7SOU) && !MJTILE_IS_YAOCHU(MJTILE_8SOU)
    &&  MJTILE_IS_YAOCHU(MJTILE_9SOU)
    &&  MJTILE_IS_YAOCHU(MJTILE_TON)  &&  MJTILE_IS_YAOCHU(MJTILE_NAN)
    &&  MJTILE_IS_YAOCHU(MJTILE_SHA)  &&  MJTILE_IS_YAOCHU(MJTILE_PEE)
    &&  MJTILE_IS_YAOCHU(MJTILE_HAKU) &&  MJTILE_IS_YAOCHU(MJTILE_HATU)
    &&  MJTILE_IS_YAOCHU(MJTILE_CHUN)
    );

/* 三元牌判定 */
MJUTILITY_STATIC_ASSERT(
       !MJTILE_IS_SANGEN(MJTILE_1MAN) && !MJTILE_IS_SANGEN(MJTILE_2MAN)
    && !MJTILE_IS_SANGEN(MJTILE_3MAN) && !MJTILE_IS_SANGEN(MJTILE_4MAN)
    && !MJTILE_IS_SANGEN(MJTILE_5MAN) && !MJTILE_IS_SANGEN(MJTILE_6MAN)
    && !MJTILE_IS_SANGEN(MJTILE_7MAN) && !MJTILE_IS_SANGEN(MJTILE_8MAN)
    && !MJTILE_IS_SANGEN(MJTILE_9MAN)
    && !MJTILE_IS_SANGEN(MJTILE_1PIN) && !MJTILE_IS_SANGEN(MJTILE_2PIN)
    && !MJTILE_IS_SANGEN(MJTILE_3PIN) && !MJTILE_IS_SANGEN(MJTILE_4PIN)
    && !MJTILE_IS_SANGEN(MJTILE_5PIN) && !MJTILE_IS_SANGEN(MJTILE_6PIN)
    && !MJTILE_IS_SANGEN(MJTILE_7PIN) && !MJTILE_IS_SANGEN(MJTILE_8PIN)
    && !MJTILE_IS_SANGEN(MJTILE_9PIN)
    && !MJTILE_IS_SANGEN(MJTILE_1SOU) && !MJTILE_IS_SANGEN(MJTILE_2SOU)
    && !MJTILE_IS_SANGEN(MJTILE_3SOU) && !MJTILE_IS_SANGEN(MJTILE_4SOU)
    && !MJTILE_IS_SANGEN(MJTILE_5SOU) && !MJTILE_IS_SANGEN(MJTILE_6SOU)
    && !MJTILE_IS_SANGEN(MJTILE_7SOU) && !MJTILE_IS_SANGEN(MJTILE_8SOU)
    && !MJTILE_IS_SANGEN(MJTILE_9SOU)
    && !MJTILE_IS_SANGEN(MJTILE_TON)  && !MJTILE_IS_SANGEN(MJTILE_NAN)
    && !MJTILE_IS_SANGEN(MJTILE_SHA)  && !MJTILE_IS_SANGEN(MJTILE_PEE)
    &&  MJTILE_IS_SANGEN(MJTILE_HAKU) &&  MJTILE_IS_SANGEN(MJTILE_HATU)
    &&  MJTILE_IS_SANGEN(MJTILE_CHUN)
    );

/* 数牌種類判定 */
/* 萬子 */
MJUTILITY_STATIC_ASSERT(
        MJTILE_TYPE_IS(MJTILE_1MAN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_1MAN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_1MAN, MJTILETYPE_SOUZU)
    &&  MJTILE_TYPE_IS(MJTILE_2MAN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_2MAN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_2MAN, MJTILETYPE_SOUZU)
    &&  MJTILE_TYPE_IS(MJTILE_3MAN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_3MAN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_3MAN, MJTILETYPE_SOUZU)
    &&  MJTILE_TYPE_IS(MJTILE_4MAN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_4MAN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_4MAN, MJTILETYPE_SOUZU)
    &&  MJTILE_TYPE_IS(MJTILE_5MAN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_5MAN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_5MAN, MJTILETYPE_SOUZU)
    &&  MJTILE_TYPE_IS(MJTILE_6MAN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_6MAN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_6MAN, MJTILETYPE_SOUZU)
    &&  MJTILE_TYPE_IS(MJTILE_7MAN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_7MAN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_7MAN, MJTILETYPE_SOUZU)
    &&  MJTILE_TYPE_IS(MJTILE_8MAN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_8MAN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_8MAN, MJTILETYPE_SOUZU)
    &&  MJTILE_TYPE_IS(MJTILE_9MAN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_9MAN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_9MAN, MJTILETYPE_SOUZU)
    );
/* 筒子 */
MJUTILITY_STATIC_ASSERT(
       !MJTILE_TYPE_IS(MJTILE_1PIN, MJTILETYPE_MANZU) &&  MJTILE_TYPE_IS(MJTILE_1PIN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_1PIN, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_2PIN, MJTILETYPE_MANZU) &&  MJTILE_TYPE_IS(MJTILE_2PIN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_2PIN, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_3PIN, MJTILETYPE_MANZU) &&  MJTILE_TYPE_IS(MJTILE_3PIN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_3PIN, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_4PIN, MJTILETYPE_MANZU) &&  MJTILE_TYPE_IS(MJTILE_4PIN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_4PIN, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_5PIN, MJTILETYPE_MANZU) &&  MJTILE_TYPE_IS(MJTILE_5PIN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_5PIN, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_6PIN, MJTILETYPE_MANZU) &&  MJTILE_TYPE_IS(MJTILE_6PIN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_6PIN, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_7PIN, MJTILETYPE_MANZU) &&  MJTILE_TYPE_IS(MJTILE_7PIN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_7PIN, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_8PIN, MJTILETYPE_MANZU) &&  MJTILE_TYPE_IS(MJTILE_8PIN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_8PIN, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_9PIN, MJTILETYPE_MANZU) &&  MJTILE_TYPE_IS(MJTILE_9PIN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_9PIN, MJTILETYPE_SOUZU)
    );
/* 索子 */
MJUTILITY_STATIC_ASSERT(
       !MJTILE_TYPE_IS(MJTILE_1SOU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_1SOU, MJTILETYPE_PINZU) &&  MJTILE_TYPE_IS(MJTILE_1SOU, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_2SOU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_2SOU, MJTILETYPE_PINZU) &&  MJTILE_TYPE_IS(MJTILE_2SOU, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_3SOU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_3SOU, MJTILETYPE_PINZU) &&  MJTILE_TYPE_IS(MJTILE_3SOU, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_4SOU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_4SOU, MJTILETYPE_PINZU) &&  MJTILE_TYPE_IS(MJTILE_4SOU, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_5SOU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_5SOU, MJTILETYPE_PINZU) &&  MJTILE_TYPE_IS(MJTILE_5SOU, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_6SOU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_6SOU, MJTILETYPE_PINZU) &&  MJTILE_TYPE_IS(MJTILE_6SOU, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_7SOU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_7SOU, MJTILETYPE_PINZU) &&  MJTILE_TYPE_IS(MJTILE_7SOU, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_8SOU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_8SOU, MJTILETYPE_PINZU) &&  MJTILE_TYPE_IS(MJTILE_8SOU, MJTILETYPE_SOUZU)
    && !MJTILE_TYPE_IS(MJTILE_9SOU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_9SOU, MJTILETYPE_PINZU) &&  MJTILE_TYPE_IS(MJTILE_9SOU, MJTILETYPE_SOUZU)
    );
/* 字牌 */
MJUTILITY_STATIC_ASSERT(
          !MJTILE_TYPE_IS(MJTILE_TON, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_TON, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_TON, MJTILETYPE_SOUZU)
       && !MJTILE_TYPE_IS(MJTILE_NAN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_NAN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_NAN, MJTILETYPE_SOUZU)
       && !MJTILE_TYPE_IS(MJTILE_SHA, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_SHA, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_SHA, MJTILETYPE_SOUZU)
       && !MJTILE_TYPE_IS(MJTILE_PEE, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_PEE, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_PEE, MJTILETYPE_SOUZU)
       && !MJTILE_TYPE_IS(MJTILE_HAKU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_HAKU, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_HAKU, MJTILETYPE_SOUZU)
       && !MJTILE_TYPE_IS(MJTILE_HATU, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_HATU, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_HATU, MJTILETYPE_SOUZU)
       && !MJTILE_TYPE_IS(MJTILE_CHUN, MJTILETYPE_MANZU) && !MJTILE_TYPE_IS(MJTILE_CHUN, MJTILETYPE_PINZU) && !MJTILE_TYPE_IS(MJTILE_CHUN, MJTILETYPE_SOUZU)
    );

/* 数牌判定 */
MJUTILITY_STATIC_ASSERT(
       MJTILE_NUMBER_IS(MJTILE_1MAN, 1) && MJTILE_NUMBER_IS(MJTILE_2MAN, 2)
    && MJTILE_NUMBER_IS(MJTILE_3MAN, 3) && MJTILE_NUMBER_IS(MJTILE_4MAN, 4)
    && MJTILE_NUMBER_IS(MJTILE_5MAN, 5) && MJTILE_NUMBER_IS(MJTILE_6MAN, 6)
    && MJTILE_NUMBER_IS(MJTILE_7MAN, 7) && MJTILE_NUMBER_IS(MJTILE_8MAN, 8)
    && MJTILE_NUMBER_IS(MJTILE_9MAN, 9)
    && MJTILE_NUMBER_IS(MJTILE_1PIN, 1) && MJTILE_NUMBER_IS(MJTILE_2PIN, 2)
    && MJTILE_NUMBER_IS(MJTILE_3PIN, 3) && MJTILE_NUMBER_IS(MJTILE_4PIN, 4)
    && MJTILE_NUMBER_IS(MJTILE_5PIN, 5) && MJTILE_NUMBER_IS(MJTILE_6PIN, 6)
    && MJTILE_NUMBER_IS(MJTILE_7PIN, 7) && MJTILE_NUMBER_IS(MJTILE_8PIN, 8)
    && MJTILE_NUMBER_IS(MJTILE_9PIN, 9)
    && MJTILE_NUMBER_IS(MJTILE_1SOU, 1) && MJTILE_NUMBER_IS(MJTILE_2SOU, 2)
    && MJTILE_NUMBER_IS(MJTILE_3SOU, 3) && MJTILE_NUMBER_IS(MJTILE_4SOU, 4)
    && MJTILE_NUMBER_IS(MJTILE_5SOU, 5) && MJTILE_NUMBER_IS(MJTILE_6SOU, 6)
    && MJTILE_NUMBER_IS(MJTILE_7SOU, 7) && MJTILE_NUMBER_IS(MJTILE_8SOU, 8)
    && MJTILE_NUMBER_IS(MJTILE_9SOU, 9)
    );

MJUTILITY_STATIC_ASSERT(
       MJTILE_IS_SAME_NUMBER(MJTILE_1MAN, MJTILE_1PIN) && MJTILE_IS_SAME_NUMBER(MJTILE_1PIN, MJTILE_1SOU)
    && MJTILE_IS_SAME_NUMBER(MJTILE_2MAN, MJTILE_2PIN) && MJTILE_IS_SAME_NUMBER(MJTILE_2PIN, MJTILE_2SOU)
    && MJTILE_IS_SAME_NUMBER(MJTILE_3MAN, MJTILE_3PIN) && MJTILE_IS_SAME_NUMBER(MJTILE_3PIN, MJTILE_3SOU)
    && MJTILE_IS_SAME_NUMBER(MJTILE_4MAN, MJTILE_4PIN) && MJTILE_IS_SAME_NUMBER(MJTILE_4PIN, MJTILE_4SOU)
    && MJTILE_IS_SAME_NUMBER(MJTILE_5MAN, MJTILE_5PIN) && MJTILE_IS_SAME_NUMBER(MJTILE_5PIN, MJTILE_5SOU)
    && MJTILE_IS_SAME_NUMBER(MJTILE_6MAN, MJTILE_6PIN) && MJTILE_IS_SAME_NUMBER(MJTILE_6PIN, MJTILE_6SOU)
    && MJTILE_IS_SAME_NUMBER(MJTILE_7MAN, MJTILE_7PIN) && MJTILE_IS_SAME_NUMBER(MJTILE_7PIN, MJTILE_7SOU)
    && MJTILE_IS_SAME_NUMBER(MJTILE_8MAN, MJTILE_8PIN) && MJTILE_IS_SAME_NUMBER(MJTILE_8PIN, MJTILE_8SOU)
    && MJTILE_IS_SAME_NUMBER(MJTILE_9MAN, MJTILE_9PIN) && MJTILE_IS_SAME_NUMBER(MJTILE_9PIN, MJTILE_9SOU)
    );

/* 最大値と無効値が有効とみなされてはいけない */
MJUTILITY_STATIC_ASSERT(!MJTILE_IS_VALID(MJTILE_MAX));
MJUTILITY_STATIC_ASSERT(!MJTILE_IS_VALID(MJTILE_INVALID));

/* 赤ドラ判定確認 コーナーケースだけ確認 */
MJUTILITY_STATIC_ASSERT(
       MJTILE_IS_AKADORA(MJTILE_1MAN | MJTILE_FLAG_AKADORA) && MJTILE_IS_AKADORA(MJTILE_9MAN | MJTILE_FLAG_AKADORA)
    && MJTILE_IS_AKADORA(MJTILE_1PIN | MJTILE_FLAG_AKADORA) && MJTILE_IS_AKADORA(MJTILE_9PIN | MJTILE_FLAG_AKADORA)
    && MJTILE_IS_AKADORA(MJTILE_1SOU | MJTILE_FLAG_AKADORA) && MJTILE_IS_AKADORA(MJTILE_9SOU | MJTILE_FLAG_AKADORA)
    && MJTILE_IS_AKADORA(MJTILE_TON  | MJTILE_FLAG_AKADORA) && MJTILE_IS_AKADORA(MJTILE_CHUN | MJTILE_FLAG_AKADORA));

/* 無効な牌は赤ドラと判定されない */
MJUTILITY_STATIC_ASSERT(!MJTILE_IS_AKADORA(MJTILE_MAX));
MJUTILITY_STATIC_ASSERT(!MJTILE_IS_AKADORA(MJTILE_INVALID));

/* 牌種の判定チェック */
static void MJTileTest_CheckTileTypeTest(void *obj)
{
  TEST_UNUSED_PARAMETER(obj);

  {
  }
}

void MJTileTest_Setup(void)
{
  struct TestSuite *suite
    = Test_AddTestSuite("MJ Tile Test Suite",
        NULL, MJTileTest_Initialize, MJTileTest_Finalize);

  Test_AddTest(suite, MJTileTest_CheckTileTypeTest);
}
