
name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: core build
      run: cd core; mkdir build; cd build; cmake ..; make
    - name: player build
      run: cd player; mkdir build; cd build; cmake ..; make
    - name: simulator build
      run: cd simulator; mkdir build; cd build; cmake ..; make
    - name: unittest
      run: cd test; mkdir build; cd build; cmake ..; make; ./mjlibtest
